### ISSUE TITLE
Wrong number of business days in June 2015

### ISSUE THREAD

**Issue by thechrisoshow** [gocardless/business#11]
Loving the gem - however I noticed that for some reason June 2015 (with the BST timezone) reports incorrect business days.

    calendar = Business::Calendar.new(working_days: %w( mon tue wed thu fri ))
    start_date = Date.parse("23 June 2015")
    end_date = Date.parse("30 June 2015")
    calendar.business_days_between(start_date, end_date) #=> 5

    (start_date..end_date).to_a.select {|d| calendar.business_day?(d)}.size #=> 6

Any ideas what's wrong? Is it only me that sees this?

**Comment by thechrisoshow** [comment]
OMG, ignore. I misunderstood how business_days_between works.

**Comment by greysteil** [comment]
No worries - thanks for filing the issue all the same!
