### ISSUE TITLE
How to update a yml file and how to use it into my own lib/data folder

### ISSUE THREAD

**Issue by realleoman** [gocardless/business#29]
Hi:

Amazing gem you have created. It's working really good. I have two questions, so I hope you can help me:

1.- Where can I find the yml files that comes along with the gem so I can edit them?
2.- How can I use my own .yml file on my lib/data directory?

Thanks for your answer.!

**Comment by nickcampbell18** [comment]
Hi @realleoman,

All of the YML files in the gem are in [lib/business/data](https://github.com/gocardless/business/tree/master/lib/business/data), if you want to see which ones we are using. To add your own, there's a [section in the README](https://github.com/gocardless/business#custom-calendars). So, if you want to add your own calendar in `/tmp/calendars/mine.yml`, you would do:

```ruby
Business::Calendar.additional_load_paths = ['/tmp/calendars']
calendar = Business::Calendar.load('mine')
```

Hope that helps!

**Comment by realleoman** [comment]
Hi @nickcampbell18  I figured it out minutes later I sent this email. Thanks for answering. You rock so hard! 🤘  Awesome gem you built!
